### PR TITLE
PLNSRVCE-783: Convert tasks to catalog

### PR DESCRIPTION
**Pull request by tkdchen**

### CODE REVIEW

**Comment by Michkov** [comment]
@lcarva @dirgim still draft but working, right now it should be just rewriting tasks into catalog format, it causes some code duplicity -> mainly in build-tasks (buildah, s2i-java, s2i-nodejs).

**Comment by lcarva** [comment]
Nice! I tried it out and am happy that `task-bundle-list` and `pipeline-bundle-list` are still being populated properly.

I did notice that the pipeline definitions no longer reference the task bundles by digest, e.g.:
```yaml
    - name: sanity-optional-label-check
      params:
        - name: POLICY_NAMESPACE
          value: optional_checks
      runAfter:
        - sanity-inspect-image
      taskRef:
        bundle: quay.io/lucarval/task-sanity-label-check:0.1
        name: sanity-label-check
```

Intentional? We have some checks in EC that ensure any task bundle is pinned to a digest.

**Comment by tkdchen** [comment]
Updates:

* `catalog/task/` --> `task/`
* task bundle with digest is injected into `taskRef`, e.g.:
  ```yaml
  - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - appstudio-init
      taskRef:
        name: git-clone
        bundle: quay.io/tkdchen/task-git-clone:0.1@sha256:6c94dfd9dae1e625d448ebfc0fde94a9f1d7f2c07feaa1691d3ee241fd9cc027
      when:
        - input: $(tasks.appstudio-init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
  ```
  Thanks Luiz for catching the issue. :+1:

**Review by zregvart — APPROVED** [review]
LGTM

**Comment by Michkov** [comment]
Failed to assign PVC, not related to this change.

/retest

**Review by Michkov — APPROVED** [review]

**Comment by Michkov** [comment]
Push pipeline failed since the repositories in quay were not created, created them manually and re-run the pipelinerun, which successfully created PRs in ec-policies and infra-deploymetns

**Pull request merged**
