### PR TITLE
Include image digest in task references

### PR DESCRIPTION
**Pull request by zregvart**
When the pipeline images are built `taskRef`'s `bundle` field is set with the reference to the bundle image containing the task identified by it's name. That image reference does not include the task bundle image digest.

This adds the task bundle image digest to the `bundle` field as well.

Fixes https://issues.redhat.com/browse/HACBS-1086

### CODE REVIEW

**Comment by lcarva** [comment]
Something is up. When I built this locally, I see that the `enterprise-contract` Pipeline refers to the `-2` task Tekton bundle, it should be `-3`. Also, any pipeline that uses one of the tasks from `-1` task Tekton bundle, appear to have an empty bundle, e.g.: `{"bundle": "", "name": "buildah"}`

Off by one error?

**Comment by zregvart** [comment]
> Off by one error?

Thanks! Fixed. I think.

**Comment by lcarva** [comment]
> > Off by one error?
> 
> Thanks! Fixed. I think.

I still see the issue :(

**Comment by zregvart** [comment]
@lcarva can you have another look, third time's the charm

**Review by lcarva — APPROVED** [review]
Works great!

**Review by Michkov — APPROVED** [review]

**Comment by zregvart** [comment]
Thanks for the review!

**Pull request merged**
