### PR TITLE
Add missing remote task

### PR DESCRIPTION
**Pull request by gbenhaim**
The ec-checks task was missing from the remote tasks annotation.

### CODE REVIEW

**Comment by hongweiliu17** [comment]
e2e in build PLR fails with
```
ummarizing 1 Failure:
  [FAIL] [build-service-suite Build templates E2E test] HACBS pipelines [It] should eventually finish successfully for component with Git source URL https://github.com/cachito-testing/pip-e2e-test [build, build-templates, HACBS, pipeline, build-templates-e2e]
  /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:198

Ran 34 of 759 Specs in 1834.582 seconds
FAIL! -- 33 Passed | 1 Failed | 20 Pending | 705 Skipped
--- FAIL: TestE2E (1834.60s)
```

**Comment by hongweiliu17** [comment]
@dheerajodha @kasemAlem Could you help check this failed e2e case in build PLR mentioned above? Thanks!

**Comment by gbenhaim** [comment]
This issue is blocking the build of a new bundle post merge.
This fix doesn't change anything that should fail the e2e tests.
I'm going to merge it.

**Pull request merged**
