### PR TITLE
fix(STONEINTG-603) remove insecure connection from curl

### PR DESCRIPTION
**Pull request by sonam1412**
curl -k runs insecure connection to the server. This is a security issue to skip SSL certificate errors by adding -k or --insecure option in curl commands. 
This PR is to remove the -k option from the curl command of the deprecated-image-check

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by MartinBasti** [comment]
We should also fix older versions of this task

**Review by jsztuka — APPROVED** [review]
lgtm

**Review by MartinBasti — APPROVED** [review]

**Pull request merged**
