### PR TITLE
fix(STONEINTG-496): remove unused tasks sast-go and sast-java-sec-check

### PR DESCRIPTION
**Pull request by hongweiliu17**
* Removed the two unused tasks.

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Review by Josh-Everett — APPROVED** [review]
LGTM pending Matt's answer in https://issues.redhat.com/browse/STONEINTG-496

**Review by jsztuka — APPROVED** [review]
lgtm

**Comment by jsztuka** [comment]
needs rebase

**Pull request merged**
