### PR TITLE
Update renovate config

### PR DESCRIPTION
**Pull request by MartinBasti**
Updating renovate config to the current state of the world

# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by kasemAlem — APPROVED** [review]

**Comment by jsztuka** [comment]
needs rebase

**Comment by MartinBasti** [comment]
> needs rebase

It first need working e2e tests, till that I can rebase indefinitely

**Review by jsztuka — APPROVED** [review]
lgtm

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by chmeliik** [comment]
FYI the PR pipeline won't work with the merge queue, trying to fix in https://github.com/redhat-appstudio/build-definitions/pull/933

**Pull request merged**
