### PR TITLE
fix: deprecated image for special images

### PR DESCRIPTION
**Pull request by srivickynesh**
Handle hacbs_test_output result output for missing images.

### CODE REVIEW

**Comment by MartinBasti** [comment]
Can we have please more elaborate description, It's not clear from commit msg what the fix is fixing.
Also it misses signed-off

**Review by MartinBasti — APPROVED** [review]

**Comment by flacatus** [comment]
Hi @srivickynesh !

We see a new silent error in some of our e2e tests.

image

**Comment by srivickynesh** [comment]
Screenshot from 2023-01-30 15-17-34

**Review by Michkov — APPROVED** [review]

**Review by flacatus — APPROVED** [review]

**Review by MartinBasti — APPROVED** [review]

**Review by jsztuka — APPROVED** [review]
lgtm

**Pull request merged**
