### PR TITLE
fix(STONEINTG-360): change violations to warnings for Clair rego policy

### PR DESCRIPTION
**Pull request by Josh-Everett**

### CODE REVIEW

**Comment by MartinBasti** [comment]
I don't understand this change, don't we miss a related change in rego policy?

**Comment by Josh-Everett** [comment]
> I don't understand this change, don't we miss a related change in rego policy?

Yes, you are correct. I was misunderstanding how conftest interprets rego policy, this is in tandem with changes in https://github.com/redhat-appstudio/hacbs-test/pull/95

**Review by MartinBasti — CHANGES_REQUESTED** [review]
Before merging, task needs updated hacbs-test image

**Comment by dirgim** [comment]
@Josh-Everett we'll first need to merge the [change to hacbs-test](https://github.com/redhat-appstudio/hacbs-test/pull/95) and then build the image, which can then be used in concert with this change.

**Comment by Josh-Everett** [comment]
> @Josh-Everett we'll first need to merge the [change to hacbs-test](https://github.com/redhat-appstudio/hacbs-test/pull/95) and then build the image, which can then be used in concert with this change.

ack @dirgim that makes sense - those changes have been merged now.

**Comment by MartinBasti** [comment]
This must be udpated to the latest hacbs-test image
```
    - name: conftest-vulnerabilities
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.14@sha256:24ccb3f35bb088c261793b84f0297ab58d5a3e13f1cea3fe5094592276d3cb6a
```

CI gating is not failing here, but it's breaking change without new image 

@dheerajodha we have some missing test coverage here, as this change should break everything

**Review by MartinBasti — APPROVED** [review]
Works like charm now

**Comment by Josh-Everett** [comment]
failing task `check-task-pipeline-repo-existence`
```
step-fail-when-repo-is-missed
Checking existence of task and pipeline bundle repositories ...
Missing pipeline bundle repo: pipeline-enterprise-contract-everything
Missing pipeline bundle repo: pipeline-enterprise-contract-slsa1
Missing pipeline bundle repo: pipeline-enterprise-contract-slsa2
Missing pipeline bundle repo: pipeline-enterprise-contract-slsa3
Please contact Build team - #forum-stonesoup-build that the missing repos should be created in https://quay.io/organization/redhat-appstudio-tekton-catalog
```

**Comment by Josh-Everett** [comment]
It looks like the [renovate pr](https://github.com/redhat-appstudio/build-definitions/pull/428) is failing under [similar circumstances](https://console-openshift-console.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/k8s/ns/tekton-ci/tekton.dev~v1beta1~PipelineRun/build-definitions-pull-request-f68qc/logs/check-task-pipeline-repo-existence).

**Comment by dheerajodha** [comment]
>@dheerajodha we have some missing test coverage here, as this change should break everything

Thanks for the tag, I'll make a note of it.

**Pull request merged**
