### PR TITLE
Add a buildah task step that generates base images sbom

### PR DESCRIPTION
**Pull request by mkosiarc**
This steps uses a python script for creating the sbom
https://github.com/redhat-appstudio/build-tasks-dockerfiles/tree/main/base-images-sbom-script

It expects 3 arguments:
1. path to the sbom file that will be updated in place with base images data
2. path to a file containing base images as taken from from the dockerfile (with preserved order)
3. path to a file containing base images with digests, generated from the output of buildah images --format '{{ .Name }}:{{ .Tag }}@{{ .Digest }}'.
The dockerfile order must be preserved as well

For more information, please read the script README

[STONEBLD-2042](https://issues.redhat.com//browse/STONEBLD-2042)

### CODE REVIEW

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

**Review by tkdchen — APPROVED** [review]

**Pull request merged**
