### PR TITLE
fix: reverting changes in tasks with  hacbs-test:feature-sast to befo…

### PR DESCRIPTION
**Pull request by jencull**
…re last edit.

Revert 2 previous changes made in stoneinteg-412. On hold to discuss next week.

### CODE REVIEW

**Review by MartinBasti — APPROVED** [review]

**Comment by sonam1412** [comment]
This is reverting the changes from https://github.com/redhat-appstudio/build-definitions/pull/440

**Review by jsztuka — APPROVED** [review]
lgtm

**Review by Josh-Everett — APPROVED** [review]

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
