### PR TITLE
PLNSRVCE-89 merge in Java dependency analyser sbom

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by gabemontero** [comment]
@mmorhun @psturc any idea where on the staging cluster I can go to look at the logs that failed in the e2e test noted at https://console-openshift-console.apps.appstudio-stage.x99m.p1.openshiftapps.com/k8s/ns/build-templates/pods/build-definitions-pull-request-tjh2w-e2e-test-pod/logs ?

the e2e logs themselves are very uninformative .... the only failed pods I see are the e2e pods with the same non-detailed failure message?

Is the typical pattern to simply try and reproduce this manually if you see a failure in CI?

@stuartwdouglas FYI I don't think we can merge your change here until we sort this out.

**Comment by psturc** [comment]
@gabemontero you should be able to watch the build PipelineRuns in the build-templates-e2e namespace on a staging cluster (if you have access to it), to get more details. Unfortunately those pipelineruns get cleaned up after the test is finished.

I have a [task in the sprint](https://issues.redhat.com/browse/PLNSRVCE-306) to add an additional flag to e2e tests to skip the cleanup in case the test fails (currently it's a default behaviour for all tests), which should help.

**Comment by gabemontero** [comment]
> @gabemontero you should be able to watch the build PipelineRuns in the build-templates-e2e namespace on a staging cluster (if you have access to it), to get more details. Unfortunately those pipelineruns get cleaned up after the test is finished.
> 
> I have a [task in the sprint](https://issues.redhat.com/browse/PLNSRVCE-306) to add an additional flag to e2e tests to skip the cleanup in case the test fails (currently it's a default behaviour for all tests), which should help.

ahhhh ... ok that helps @psturc thanks :-)

look forward to https://issues.redhat.com/browse/PLNSRVCE-306

**Comment by gabemontero** [comment]
ok let's see if I can find that pipeline run with your retest

**Comment by gabemontero** [comment]
https://console-openshift-console.apps.appstudio-stage.x99m.p1.openshiftapps.com/k8s/ns/build-templates/pods/build-definitions-pull-request-vzkwq-build-container-pod/logs

**Comment by stuartwdouglas** [comment]
Ah, I was thinking this was just for Java. It's likely an issue with the Java sbom not existing for non-Java builds.

**Comment by stuartwdouglas** [comment]
@gabemontero should be fixed now

**Pull request merged**
