### PR TITLE
feat(HACBS-1883): Create label to identify the build task for each pipeline.

### PR DESCRIPTION
**Pull request by joejstuart**
The label will be used by a policy to identify which build pipeline ran.

https://issues.redhat.com/browse/HACBS-1883

### CODE REVIEW

**Comment by Michkov** [comment]
This is being set on pipeline level:
https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/template-build/template-build.yaml#L6-L8

https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/nodejs-builder/patch.yaml#L8-L10
https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/java-builder/patch.yaml#L8-L10
https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/fbc-builder/patch.yaml#L8-L10
https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/docker-build/patch.yaml#L8-L10

**Comment by joejstuart** [comment]
> This is being set on pipeline level: https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/template-build/template-build.yaml#L6-L8
> 
> https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/nodejs-builder/patch.yaml#L8-L10 https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/java-builder/patch.yaml#L8-L10 https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/fbc-builder/patch.yaml#L8-L10 https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/docker-build/patch.yaml#L8-L10

This label will be used to identify which build ran when an attestation is examined. Setting the label at the task ensures that a user cannot modify it in the pipelineRun when the taskRef points to a bundle.

**Review by lcarva — APPROVED** [review]

**Comment by lcarva** [comment]
Looks like this PR is stalled. Next steps?

**Review by Michkov — APPROVED** [review]

**Comment by Michkov** [comment]
@joejstuart must be public user of redhat-appstudio org - https://pipelinesascode.com/docs/guide/running/

**Review by lcarva — APPROVED** [review]

**Pull request merged**
