### PR TITLE
Remove deprecated contract task and related script

### PR DESCRIPTION
**Pull request by simonbaird**

### CODE REVIEW

**Comment by simonbaird** [comment]
I feel like we don't have to merge it right away, but here's what the "Remove old junk" PR might look like. I didn't want to figure out which parts of appstudio-utils/util-scripts/lib/fetch/tekton.sh were still useful, so I just left it alone. There are arguments for removing the rekor stuff and its test coverage I guess. What do you think?

**Comment by joejstuart** [comment]
>  There are arguments for removing the rekor stuff and its test coverage I guess. What do you think?
 I vote for leaving them at this point. Just because ec-policies is focused on using attestations, doesn't mean there won't be another policy that needs to validate cluster information. Maybe... And the scripts contain useful utilities.

**Comment by simonbaird** [comment]
Yeah, that's my thinking too. E.g the shorten-sha function - it's too good to throw away.. :)

**Comment by simonbaird** [comment]
Also there's also the future "validate a pipeline definition" functionality that would need to use data from somewhere other than an attestation fetched with cosign, so that's an argument for keeping some handy cluster fetch functions in case they become useful.

**Comment by lcarva** [comment]
+1 to delete deprecated stuff. It's less things we have to worry about. If we get nostalgic, we can always look at the git history :grin:

**Comment by simonbaird** [comment]
It says no conflicts, so let's merge.

**Pull request merged**
