### PR TITLE
Revert "Removing unneeded tasks from FBC pipeline (#865)"

### PR DESCRIPTION
**Pull request by ralphbean**
This reverts commit 117850230cc180562e2fd6116b2c7858c8f20bab.

The original change is essentially correct, but for unknown reasons I think that https://github.com/redhat-appstudio/e2e-tests/pull/1065 is not effective in the way we thought it should be. My theory is that 117850230cc180562e2fd6116b2c7858c8f20bab is currently causing e2e tests to fail in the build-definitions repo for all other PRs.

### CODE REVIEW

**Review by tkdchen — APPROVED** [review]

**Comment by mmorhun** [comment]
We are trying to fix tests, so I'd like to postpone merging.

**Comment by mmorhun** [comment]
The fix is confirmed to work and merged into tests repo. Waiting on https://github.com/redhat-appstudio/build-definitions/pull/919 to apply new tests image

**Comment by mmorhun** [comment]
Closing since the fix is applied and tested in https://github.com/redhat-appstudio/build-definitions/pull/918

**Pull request closed without merging**
