### PR TITLE
Migrate to tekton API v1

### PR DESCRIPTION
**Pull request by tkdchen**

### CODE REVIEW

**Comment by zregvart** [comment]
I think the update of Tekton Pipelines version [here](https://github.com/redhat-appstudio/build-definitions/blob/06784ffb837be23caeab4248bf563fa79b9b27f5/task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh#L26) is required to pass the shellspec tests.

**Comment by tkdchen** [comment]
> I think the update of Tekton Pipelines version [here](https://github.com/redhat-appstudio/build-definitions/blob/06784ffb837be23caeab4248bf563fa79b9b27f5/task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh#L26) is required to pass the shellspec tests.

@zregvart Is there any requirement for the tekton release version for running the tests? Any idea about the root cause of the failures?

**Comment by zregvart** [comment]
For the buildah-remote check it seems that the multi-platform controller change is needed [here](https://github.com/redhat-appstudio/multi-platform-controller/blob/dc43d6e0cdd711a06c46c43ebb081e37777a2009/cmd/taskgen/main.go#L19).

@stuartwdouglas can you have a look please?

**Comment by stuartwdouglas** [comment]
https://github.com/redhat-appstudio/multi-platform-controller/pull/79 once this is in you can add the update to the new image in the generate script.

**Comment by tkdchen** [comment]
@zregvart Hi, thanks for your feedback. What I need to do for running tkn-bundle_spec.sh locally is to launch a k8s cluster and install shellspec?

**Comment by zregvart** [comment]
> @zregvart Hi, thanks for your feedback. What I need to do for running tkn-bundle_spec.sh locally is to launch a k8s cluster and install shellspec?

The requirements are [shellspec](https://shellspec.info/) and [kind](https://kind.sigs.k8s.io/), there are docs on running the tests [here](https://github.com/redhat-appstudio/build-definitions/blob/main/task/tkn-bundle/0.1/TESTING.md).

**Comment by zregvart** [comment]
Odd, the shellspec tests pass for me locally from this branch. I've noticed that [workflow ran](https://github.com/redhat-appstudio/build-definitions/actions/runs/6811686498/job/18522528253?pr=671) with revision d611548b8225ca4ea031b998125c2928fd5ee923, and the revision I'm expecting to be is b46d7083a50577904754f0d36d8b0a42ef8561a9.

If I test with b46d7083a50577904754f0d36d8b0a42ef8561a9 the tests succeed, with d611548b8225ca4ea031b998125c2928fd5ee923 I can see four instances of `taskResults` that should be `results`.

Here is what I tried.

As on GitHub, this fails (commands copied over from the workflow run):

```shell
cd $(mktemp -d)
git init .
git remote add origin https://github.com/redhat-appstudio/build-definitions
git -c protocol.version=2 fetch --prune --no-recurse-submodules origin '+refs/heads/*:refs/remotes/origin/*' '+refs/tags/*:refs/tags/*' +d611548b8225ca4ea031b998125c2928fd5ee923:refs/remotes/pull/671/merge
git checkout --progress --force refs/remotes/pull/671/merge
git log -1 --format='%H' # prints d611548b8225ca4ea031b998125c2928fd5ee923
hack/test-shellspec.sh # fails
```

And using the branch directly succeeds:

```shell
cd $(mktemp -d)
git clone https://github.com/tkdchen/build-definitions .
git switch origin/migrate-to-tekton-api-v1
git log -1 --format='%H' # prints b46d7083a50577904754f0d36d8b0a42ef8561a9
hack/test-shellspec.sh # succeeds
```

**Comment by tkdchen** [comment]
@zregvart Both before and after the latest force push, I succeeded in running the tests locally, but the CI job still failed. PR is based on fa51dc920c390b22005f807073932907c76409a3 as of writing this comment.

**Comment by tkdchen** [comment]
@zregvart How to read these error messages:

```
2023-11-13T03:17:26.2063622Z ##[error]The output should include Added Task: test1 to image
expected "" to include "Added Task: test1 to image"

::error file=spec/tkn-bundle_spec.sh,line=104,endLine=104,title=The output should include Added Task: test2 to image::The output should include Added Task: test2 to image
expected "" to include "Added Task: test2 to image"
```

I have no idea why "The output should include Added Task: test2 to image" is repeated twice, and why the expected string is empty `expected ""` and what it is related to.

**Comment by zregvart** [comment]
> @zregvart How to read these error messages?
> ```
> 2023-11-13T03:17:26.2063622Z ##[error]The output should include Added Task: test1 to image
> expected "" to include "Added Task: test1 to image"

This is the default error output

> ::error file=spec/tkn-bundle_spec.sh,line=104,endLine=104,title=The output should include Added Task: test2 to image::The output should include Added Task: test2 to image
> expected "" to include "Added Task: test2 to image"
> 
> ...
> ```
 > I have no idea why "The output should include Added Task: test2 to image" is repeated twice, and why the expected string is empty `expected ""` and what it is related to.

This is the same output formatted as [GitHub annotations](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message)

The error seems to be related to the version of the `tkn` CLI used in the GitHub Workflow. I can see that the version being installed/used [is 0.18.0](https://github.com/redhat-appstudio/build-definitions/actions/runs/6847497618/job/18615869573?pr=671#step:3:24). Changing `.github/workflows/shellspec.yaml` to specify a newer version should help:

```diff
diff --git a/.github/workflows/shellspec.yaml b/.github/workflows/shellspec.yaml
index b863718..338dc7a 100644
--- a/.github/workflows/shellspec.yaml
+++ b/.github/workflows/shellspec.yaml
@@ -21,6 +21,8 @@ jobs:
           fetch-depth: 0
 
       - uses: jerop/tkn@v0.1.0
+        with:
+          version: v0.33.0
 
       - name: Shellspec
         run: hack/test-shellspec.sh
```

The other issue from my comment above is still perplexing to me.

**Review by stuartwdouglas — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]
LGTM

**Comment by tkdchen** [comment]
Rebased. Commit 5a81df6 is probably due to the rebase. No other change.

**Pull request merged**
