### PR TITLE
Add latest tag to hacbs-test images

### PR DESCRIPTION
**Pull request by srivickynesh**
Image tag change from hacbs-test:stable to hacbs-test:latest.

### CODE REVIEW

**Comment by jsztuka** [comment]
Where the `stable` tag will be used then?

**Comment by srivickynesh** [comment]
changes are updated to the latest tag. see the detailed list of tag usage [here](https://quay.io/repository/redhat-appstudio/hacbs-test?tab=tags). we can still use the stable tag, but it won't have recently merged changes in the image.

**Review by jsztuka — APPROVED** [review]
LGTM

**Pull request merged**
