### PR TITLE
Give write permission to e2e-tests task

### PR DESCRIPTION
**Pull request by tkdchen**
[STONEBLD-1832](https://issues.redhat.com//browse/STONEBLD-1832)

Pull secret is required to be available for the e2e tests in order to
fetch image data from registry.redhat.io. The task needs the capability
in order to write the registry authentication credential into auth file.

### CODE REVIEW

**Comment by chmeliik** [comment]
> Pull secret is required to be available for the e2e tests in order to fetch image data from registry.redhat.io.

How is that related to the changes in this PR?

**Comment by tkdchen** [comment]
The pull secret has to be written into the default auth file. What I found is, without the capability, it fails to write.

**Comment by mmorhun** [comment]
@tkdchen it would be nice to have the above in PR description. A link to docs or your findings would be a bonus.

**Comment by tkdchen** [comment]
@mmorhun Updated the commit message, PTAL. Also, rebased.

**Comment by mkosiarc** [comment]
Would it be better to change the short commit message as well? Instead of "Run e2e tests to check including parent sources" to "Give the e2e-test task write permissions" or  something about updating the permissions?

**Review by mkosiarc — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]
/lgtm

**Comment by tkdchen** [comment]
e2e-tests failure

```
[e2e-tests : e2e-test]   [FAILED] Expected success, but got an error:
[e2e-tests : e2e-test]       <*errors.errorString | 0xc000429b00>: 
[e2e-tests : e2e-test]       pipelineTaskName "clair-scan" not found in PipelineRun fbc-sample-repo-otis-dq9tx/build-templates-e2e
[e2e-tests : e2e-test]       {
[e2e-tests : e2e-test]           s: "pipelineTaskName \"clair-scan\" not found in PipelineRun fbc-sample-repo-otis-dq9tx/build-templates-e2e",
[e2e-tests : e2e-test]       }
[e2e-tests : e2e-test]   In [It] at: /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:372 @ 04/01/24 02:00:45.002
[e2e-tests : e2e-test] ------------------------------
[e2e-tests : e2e-test] SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
[e2e-tests : e2e-test] 
```

**Pull request merged**
