### PR TITLE
Update OWNERS files and remove cleanup-build-directories task

### PR DESCRIPTION
**Pull request by Michkov**
- set owner team in OWNERS file
- remove unused cleanup-build-directories task

### CODE REVIEW

**Comment by MartinBasti** [comment]
Would be nice to have unrelated changes in separate commits

**Comment by psturc** [comment]
@MartinBasti what unrelated changes (that are not mentioned in the commit) do you mean?

**Comment by MartinBasti** [comment]
Updating OWNERS and removal of task are in the same commit, 2 unrelated changes to me

**Comment by MartinBasti** [comment]
but whatever in this case, but in future it would be nice to keep it separated, it's much more pleasant to read git history and blame with more complicated patches

**Review by MartinBasti — APPROVED** [review]

**Comment by Michkov** [comment]
Rebased and split into two commits

**Pull request merged**
