### PR TITLE
RHTAP gitops PR pipeline

### PR DESCRIPTION
**Pull request by chmeliik**
# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Comment by chmeliik** [comment]
Tested in https://github.com/acmiel-rhtap/rhtap-idk-gitops/pull/1 (the pipeline is used in https://github.com/acmiel-rhtap/rhtap-idk-gitops/blob/main/.tekton/on-pull-request-promotion.yaml)

**Review by jduimovich — COMMENTED** [review]
The "reasonable" default for the cosign key should be in the pipeline namespace
```
    - description: The public key that EC should use to verify signatures
      name: ec-public-key
      type: string
      default: "k8s://$(context.pipelineRun.namespace)/cosign-pub"
```

**Review by jduimovich — APPROVED** [review]

**Comment by chmeliik** [comment]
image

I'm going to dismiss them with "The communication occurs within the cluster-internal network." Sounds good?

**Comment by chmeliik** [comment]
re-tested newest changes in https://github.com/acmiel-rhtap/rhtap-foo-gitops/pull/1

the pipelineRun failed because the bootstrap images are not passing EC validation (to be addressed in a follow-up), but the functionality works as intended

**Review by mmorhun — APPROVED** [review]

**Pull request merged**
