### PR TITLE
Make the Buildah Task "tekton chains" friendly

### PR DESCRIPTION
**Pull request by Michkov**

### CODE REVIEW

**Review by jduimovich — APPROVED** [review]
This is a good change.
Note, that this Task was a copy of the upstream TektonHub Task 
TODO: propagate changes to that task upstream. 
TODO: We also need to add "CI" to check API assumptions for tasks (input API as well as results by TASK) or we evolve Chains to be more configurable

**Comment by Michkov** [comment]
MR already in the catalog -> https://github.com/tektoncd/catalog/pull/932

**Comment by jduimovich** [comment]
> MR already in the catalog -> https://github.com/tektoncd/catalog/pull/932

Thanks, I had not seen this change. 
The second part, grabbing from the hub and packaging it (and verifying it as valid is TODO
)

**Comment by sbose78** [comment]
Thanks @Michkov and @jduimovich 👍 
Vincent and folks are on the thread, should go into our product soon-ish :)

**Pull request merged**
