### PR TITLE
fix: add securityContext in e2e-test task for sbom check failure

### PR DESCRIPTION
**Pull request by tisutisu**
Added securityContext in e2e-test task for sbom check failure for hermatic builds

### CODE REVIEW

**Review by psturc — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]
LGTM

**Review by Michkov — CHANGES_REQUESTED** [review]
do not use personal image

**Comment by tisutisu** [comment]
> do not use personal image

@Michkov this personal image is temporary measure to unblock others since https://github.com/redhat-appstudio/e2e-tests/pull/428 can take longer time..we can revert once that gets merged.. also this PR is completing changes in e2e-tests  https://github.com/redhat-appstudio/e2e-tests/pull/424 which can cause failures in PR checks

**Review by Michkov — APPROVED** [review]

**Pull request merged**
