### PR TITLE
Change no-op checks from SKIPPED to SUCCESS

### PR DESCRIPTION
**Pull request by lcarva**
Ref: [STONEINTG-681](https://issues.redhat.com//browse/STONEINTG-681)

### CODE REVIEW

**Comment by lcarva** [comment]
Still a draft because I need to test it and verify if e2e tests need any changes.

**Comment by lcarva** [comment]
I don't see anything in e2e that checks for SKIPPED so likely no changes there.

**Review by zregvart — APPROVED** [review]

**Comment by lcarva** [comment]
# Testing Notes

I've performed the following using a kind cluster, as these changes shouldn't be OpenShift specific. From what I can tell, it is working as expected. I'll go ahead and mark this PR out of draft.

## deprecated-image-check

Create Task definition in cluster:
```
oc apply -f task/deprecated-image-check/0.3/deprecated-image-check.yaml
```

Start a TaskRun and inspect the results. Example:
```
$ tkn task start deprecated-image-check --param BASE_IMAGES_DIGESTS="" --use-param-defaults --showlog
TaskRun started: deprecated-image-check-run-d9p4m
Waiting for logs to be available...
[check-images] {"result":"SUCCESS","timestamp":"1699303314","note":"Task deprecated-image-check success: No base images to check.","namespace":"required_checks","successes":0,"failures":0,"warnings":0}

$ oc get tr deprecated-image-check-run-d9p4m -o json | jq '.status.results'
[
  {
    "name": "TEST_OUTPUT",
    "type": "string",
    "value": "{\"result\":\"SUCCESS\",\"timestamp\":\"1699303314\",\"note\":\"Task deprecated-image-check success: No base images to check.\",\"namespace\":\"required_checks\",\"successes\":0,\"failures\":0,\"warnings\":0}\n"
  }
]
```

## sast-snyk-check

First, we need a volume that contains some source code. Do this by first creating a PVC:
```
cat << EOF | oc apply -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
EOF
```

Second, create the git-clone Task in-cluster so we can populate the volume:
```bash
oc apply -f task/git-clone/0.1/git-clone.yaml
```

And, trigger a TaskRun for the git-clone Task using our volume:
```bash
tkn task start git-clone --use-param-defaults \
  --param url=https://github.com/MartinBasti/data-only-test-container.git \
  --param revision=main \
  -w name=output,claimName=source \
  --showlog
```

Next, login to create a snyk token, and create the snyk secret:
```bash
snyk auth
oc create secret generic snyk-secret --from-literal=snyk_token=`snyk config get api`
```

Create the sast-snyk-check Task in cluster:
```bash
oc apply -f task/sast-snyk-check/0.1/sast-snyk-check.yaml
```

Finally, start a TaskRun for the sast-snyk-check Task using the same volume as the git-clone TaskRun.
Example:
```
$ tkn task start sast-snyk-check --use-param-defaults -w name=workspace,claimName=source --showlog
TaskRun started: sast-snyk-check-run-82d2w
Waiting for logs to be available...
[sast-snyk-check] {"result":"SKIPPED","timestamp":"1699303729","note":"Task sast-snyk-check skipped: Snyk code test found zero supported files.","namespace":"default","successes":0,"failures":0,"warnings":0}

$ oc get tr sast-snyk-check-run-82d2w -o json | jq '.status.results'
[
  {
    "name": "TEST_OUTPUT",
    "type": "string",
    "value": "{\"result\":\"SUCCESS\",\"timestamp\":\"1699303975\",\"note\":\"Task sast-snyk-check success: Snyk code test found zero supported files.\",\"namespace\":\"default\",\"successes\":0,\"failures\":0,\"warnings\":0}\n"
  }
]
```

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
