### PR TITLE
Let renovate bot pin ec-cli image

### PR DESCRIPTION
**Pull request by lcarva**

### CODE REVIEW

**Comment by lcarva** [comment]
@MartinBasti , @Michkov ptal

**Comment by MartinBasti** [comment]
we don't want to pin digest for everything
https://github.com/redhat-appstudio/build-definitions/blob/main/task/clamav-scan/0.1/clamav-scan.yaml#L147  this must stay floating tag (the same for Clair task) because it's updated daily

**Comment by lcarva** [comment]
I wonder if I just put a digest now, then renovate bot will automatically keep that up to date :thinking:

**Comment by MartinBasti** [comment]
IIrC it will, it does pinning for cachi2 image

**Comment by lcarva** [comment]
Updated the approach.

**Review by MartinBasti — APPROVED** [review]

**Pull request merged**
