### PR TITLE
Use official tkn-cli image

### PR DESCRIPTION
**Pull request by lcarva**
Ref: https://issues.redhat.com/browse/EC-425

# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by zregvart — APPROVED** [review]

**Comment by lcarva** [comment]
@zregvart , I wonder if the shellspec failures are due to that image requiring authentication. Not sure how to plumb creds through.

**Comment by lcarva** [comment]
This is gonna require a bit of work to get the shellspec tests to work due to the creds problem. Separated the yamllint fix into its own PR: https://github.com/redhat-appstudio/build-definitions/pull/828

**Comment by zregvart** [comment]
> @zregvart , I wonder if the shellspec failures are due to that image requiring authentication. Not sure how to plumb creds through.

Yeah, starting the setup pod timed out, which is most likely because pulling the image failed. The image from the setup pod is the one [used in the task](https://github.com/redhat-appstudio/build-definitions/blob/65973c2a0dae609ec84263aa3d1806e6ab7af6c4/task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh#L80).

Not sure how to pass credentials to a pull request, running this on the pull request Tekton pipeline might be an option. We need to make sure not to leak the pull secret.

**Comment by lcarva** [comment]
The e2e tests are failing. I believe it's because it's taking Chains about 14 minutes to create the attestation :scream:

**Pull request merged**
