### PR TITLE
fix: check prod repositories on pull-request

### PR DESCRIPTION
**Pull request by Michkov**
During Pull-request check we should check production repositories so then we can reveal that some repository is missing before merging.

### CODE REVIEW

**Comment by Michkov** [comment]
```
Checking existence of task and pipeline bundle repositories ...
Missing task bundle repo: task-tkn-bundle
Missing pipeline bundle repo: pipeline-docker-build cc2ccbbd2d8cfdf851f336a3495283f14458bac0
Missing pipeline bundle repo: pipeline-enterprise-contract cc2ccbbd2d8cfdf851f336a3495283f14458bac0
Missing pipeline bundle repo: pipeline-fbc-builder cc2ccbbd2d8cfdf851f336a3495283f14458bac0
Missing pipeline bundle repo: pipeline-java-builder cc2ccbbd2d8cfdf851f336a3495283f14458bac0
Missing pipeline bundle repo: pipeline-nodejs-builder cc2ccbbd2d8cfdf851f336a3495283f14458bac0
Missing pipeline bundle repo: pipeline-tekton-bundle-builder cc2ccbbd2d8cfdf851f336a3495283f14458bac0
```
So task detection is working properly, but pipeline need to be fixed

**Review by zregvart — APPROVED** [review]

**Comment by Michkov** [comment]
@zregvart the final message added.

**Comment by Michkov** [comment]
repos created

/retest

**Comment by zregvart** [comment]
Looks like permissions need to be tweaked:
```
buildpipelineselectors.appstudio.redhat.com "build-pipeline-selector" is forbidden: User "system:serviceaccount:tekton-ci:pipeline" cannot get resource "buildpipelineselectors" in API group "appstudio.redhat.com" in the namespace "build-service"
```

**Comment by Michkov** [comment]
Yop, we are working on it - https://github.com/redhat-appstudio/e2e-tests/pull/330

**Pull request merged**
