### PR TITLE
feat(STONEINTG-415): optional-label-check should be skipped by default

### PR DESCRIPTION
**Pull request by jsztuka**
This change will allow optional label check to be run only in case that the parameter: **skip-optional** is set to "false".

### CODE REVIEW

**Comment by jsztuka** [comment]
Screenshot from 2023-05-10 15-49-45
optional-label-check is skipped

**Review by MartinBasti — APPROVED** [review]
LGTM but needs rebase

**Comment by sbose78** [comment]
Curious, what are the optional label checks that we are skipping/not skipping ?

**Comment by dirgim** [comment]
> Curious, what are the optional label checks that we are skipping/not skipping ?

The optional checks include the [inherited labels](https://redhat-appstudio.github.io/docs.stonesoup.io/Documentation/main/concepts/testing_applications/surface-level_tests/#inherited-label-checks) and [optional labels](https://redhat-appstudio.github.io/docs.stonesoup.io/Documentation/main/concepts/testing_applications/surface-level_tests/#optional-label-checks).

**Comment by sbose78** [comment]
Looks good 👍

**Pull request merged**
