### PR TITLE
fix(STONEINTG-233): rename deprecated base image check task

### PR DESCRIPTION
**Pull request by dirgim**
* rename the task to deprecated-base-image-check

### CODE REVIEW

**Review by hongweiliu17 — APPROVED** [review]
LGTM

**Comment by dheerajodha** [comment]
now that the [other PR](https://github.com/redhat-appstudio/build-definitions/pull/365) is merged, we have a conflict in this PR.

**Comment by dheerajodha** [comment]
The test fails with:
```
Checking existence of task and pipeline bundle repositories ...
Missing task bundle repo: task-deprecated-base-image-check
Please contact Build team - #forum-stonesoup-build that the missing repos should be created in https://quay.io/organization/redhat-appstudio-tekton-catalog
```

**Comment by dirgim** [comment]
Closing in favor of #379

**Pull request closed without merging**
