### PR TITLE
fix: remove \n from image_url generated by build job

### PR DESCRIPTION
**Pull request by hongweiliu17**
I meet error as below in `sbom-json-check` task
```
failed to create task run pod "nodejs-builder-run-krzcv-sbom-json-check": Pod "nodejs-builder-run-krzcv-sbom-json-check-pod" is invalid: spec.containers[1].image: Invalid value: "quay.io/hongweiliu/single-nodejs-app:f623a43\n": must not have leading or trailing whitespace. Maybe missing or invalid Task default/sbom-json-check
```
This pr is to remove the  `\n` in `results.IMAGE_URL`.

Signed-off-by: Hongwei Liu hongliu@redhat.com

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Review by lcarva — APPROVED** [review]
Nice!

**Comment by lcarva** [comment]
Is [e2e-test](https://console-openshift-console.apps.appstudio-stage.x99m.p1.openshiftapps.com/k8s/ns/build-templates/tekton.dev~v1beta1~PipelineRun/build-definitions-pull-request-bzj66/logs/e2e-test) expected to fail?

**Comment by hongweiliu17** [comment]
> 
Not, it is not expected. Is the error caused by timeout error?

**Comment by Michkov** [comment]
Not related to this change, looking what is wrong.

**Review by Michkov — APPROVED** [review]

**Pull request merged**
