### PR TITLE
RHTAPBUGS-864: Improve deprecated-image-check UX + bugfixes

### PR DESCRIPTION
**Pull request by MartinBasti**
See detailed changes commit by commit

Output examples:

No images to be checked:
```
{"result":"SKIPPED","timestamp":"1698047951","note":"Task deprecated-image-check skipped: No base images found.","namespace":"required_checks","successes":0,"failures":0,"warnings":0}
```

Successful check:
```
Querying Red Hat Catalog for registry.access.redhat.com/ubi8/go-toolset:1.19.13-2.1697656138@sha256:6c2c40207abfef2e46426f39c7fe0aca177b9da73d2b223bc0ddc7c5c56485c4.
Running conftest using /project/repository/ policy, required_checks namespace.
[
	{
		"filename": "/tmp/ubi8/go-toolset/repository_data.json",
		"namespace": "required_checks",
		"successes": 1
	}
]
[SUCCESS] Image registry.access.redhat.com/ubi8/go-toolset is valid
{"result":"SUCCESS","timestamp":"1698055574","note":"Task deprecated-image-check completed: Check result for task result.","namespace":"required_checks","successes":1,"failures":0,"warnings":0}
```

Failed check:
```
Querying Red Hat Catalog for registry.access.redhat.com/ubi8/python-38:1-131@sha256:74e5b2d063d424cb06f8e41ef1983a94b1cb890e62ec656c52e81074be21c15e.
Running conftest using /project/repository/ policy, required_checks namespace.
[
	{
		"filename": "/tmp/ubi8/python-38/repository_data.json",
		"namespace": "required_checks",
		"successes": 0,
		"failures": [
			{
				"msg": "The container image shouldn't be built from a repository that is marked as 'Deprecated' in COMET.",
				"metadata": {
					"details": {
						"description": "Deprecated images are no longer maintained and will accumulate security vulnerabilities without releasing a fixed version.",
						"name": "image_repository_deprecated",
						"url": "https://source.redhat.com/groups/public/portfolio-programs-group/container_factory_blog/dont_build_on_deprecated_images"
					}
				}
			}
		]
	}
]
[FAILURE] Image registry.access.redhat.com/ubi8/python-38 has been deprecated
{"result":"FAILURE","timestamp":"1698056820","note":"Task deprecated-image-check completed: Check result for task result.","namespace":"required_checks","successes":0,"failures":1,"warnings":0}
```

Warning:
```
Querying Red Hat Catalog for docker.io/library/node:latest@sha256:bf718fc580177cd927173c8617cf7f527a1b7f62c7de882ee17a42d065f4b70e.
[WARNING] Registry/image docker.io/library/node not found in Red Hat Catalog. Task cannot provide results if image is deprecated.
{"result":"WARNING","timestamp":"1698067298","note":"Task deprecated-image-check completed: Check result for task result.","namespace":"required_checks","successes":0,"failures":0,"warnings":0}
```

### CODE REVIEW

**Review by jsztuka — APPROVED** [review]
LGTM, just rebase is needed.

**Comment by sonam1412** [comment]
which jira ticket this belongs to ?

**Comment by MartinBasti** [comment]
RHTAPBUGS-864

**Review by dirgim — APPROVED** [review]
LGTM, do we need to check with Enterprise Contract how the `WARNING` result will be handled in their checks for this task?

**Comment by lcarva** [comment]
On the EC side, we don't treat the `deprecated-image-check` any differently. A warning result should trigger a [test.no_test_warnings](https://enterprisecontract.dev/docs/ec-policies/release_policy.html#test__no_test_warnings) warning in EC.

Thank you for checking in!

**Pull request merged**
