### PR TITLE
Fix indentation in update-infra-deployments task

### PR DESCRIPTION
**Pull request by mmorhun**

### CODE REVIEW

**Review by avi-biton — APPROVED** [review]
LGTM

**Review by chmeliik — APPROVED** [review]

**Comment by mmorhun** [comment]
Rebased and solved conflicts

**Review by gabemontero — APPROVED** [review]
/lgtm

thanks for cleaning up my incorrect indentation @mmorhun

**Review by tkdchen — APPROVED** [review]

**Comment by mmorhun** [comment]
Well, it's just formatting changes and yaml-linter check succeeded. I think it's ok to merge if we have someone with permissions to do so.

**Comment by avi-biton** [comment]
> Well, it's just formatting changes and yaml-linter check succeeded. I think it's ok to merge if we have someone with permissions to do so.

Who can we approach to merge it?

**Comment by gbenhaim** [comment]
I can merge it. I've tried to debug the failing tests for few ours. The thing that is common is that the test waits for a piplinerun and it doesn't find it. I looked in splunk and I see that the pipeline run was created and 15 minutes later got delete by tekton results watcher. This is way the test failed.
Could be a bug in the test that doesn't handle pipelines that got deleted.

**Comment by gbenhaim** [comment]
Since the failure is unrelated to the change and we must make progress today I'm going to merge it.

**Pull request merged**
