### PR TITLE
RHTAPSRE-405: Custom CA bundle for git-clone

### PR DESCRIPTION
**Pull request by gbenhaim**
Support custom CA bundle in the git-clone task.
Required when cloning using HTTPs from an SCM that has self-signed certificate.

### CODE REVIEW

**Review by MartinBasti — APPROVED** [review]

**Comment by gbenhaim** [comment]
@chmeliik I didn't find any other way to do it.

**Comment by gbenhaim** [comment]
@chmeliik here is the openshift documentation I followed https://docs.openshift.com/container-platform/4.14/networking/configuring-a-custom-pki.html#nw-proxy-configure-object_configuring-a-custom-pki

**Review by chmeliik — APPROVED** [review]

**Comment by chmeliik** [comment]
> @chmeliik I didn't find any other way to do it.

Ok. Just beware that other tasks will need corresponding changes too.

**Comment by MartinBasti** [comment]
Technically users could define pod templates in pipeline definition and mount CA there for every pod, but that's not something we should have at task level though.

**Pull request merged**
