### PR TITLE
Fix yaml lint errors

### PR DESCRIPTION
**Pull request by lcarva**
# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Comment by lcarva** [comment]
ec-tasks is failing because the image used by EC is gone... This should fix it: https://github.com/redhat-appstudio/infra-deployments/pull/3282

**Review by chmeliik — APPROVED** [review]
Thanks for the fix! :taco: 

I don't suppose you know why the checks have suddenly started working again? We had a bug for it https://issues.redhat.com/browse/STONEBLD-2167

**Comment by lcarva** [comment]
I think it was because the other PRs were from branches that were behind. That's my guess anyways.

**Pull request merged**
