### PR TITLE
remove HACBS prefix from build def, L68-71

### PR DESCRIPTION
**Pull request by jencull**

### CODE REVIEW

**Comment by dirgim** [comment]
@jencull thanks for opening this PR - the changes for the `parse_hacbs_test_output` call will also need to be done in the following files:

-  [sast-snyk-check.yaml](https://github.com/redhat-appstudio/build-definitions/blob/main/task/sast-snyk-check/0.1/sast-snyk-check.yaml)
- [sast-go.yaml](https://github.com/redhat-appstudio/build-definitions/blob/main/task/sast-go/0.1/sast-go.yaml)
- [sast-java-sec-check.yaml](https://github.com/redhat-appstudio/build-definitions/blob/main/task/sast-java-sec-check/0.1/sast-java-sec-check.yaml)

**Review by dirgim — APPROVED** [review]
LGTM

**Review by dheerajodha — APPROVED** [review]
LGTM

**Pull request merged**
