### PR TITLE
Remove label-check task

### PR DESCRIPTION
**Pull request by lcarva**
The checks performed by the label-check Task are now performed by the Enterprise Contract. This is done by querying the OCI registry.

https://issues.redhat.com/browse/HACBS-2401

### CODE REVIEW

**Comment by lcarva** [comment]
The updated template produces a few different Tekton Pipelines. Use the following to compare those:

```
diff -u \
  <(kustomize build https://github.com/redhat-appstudio/build-definitions/pipelines) \
  <(kustomize build https://github.com/lcarva/build-definitions/pipelines?ref=HACBS-2401)
```

Which produces the following:

```diff
--- /dev/fd/63	2023-07-31 14:04:40.506859191 -0400
+++ /dev/fd/62	2023-07-31 14:04:40.507859209 -0400
@@ -190,37 +190,6 @@
     workspaces:
     - name: source
       workspace: workspace
-  - name: label-check
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-checks)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
-  - name: optional-label-check
-    params:
-    - name: POLICY_NAMESPACE
-      value: optional_checks
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-optional)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
   - name: deprecated-base-image-check
     params:
     - name: BASE_IMAGES_DIGESTS
@@ -781,37 +750,6 @@
     workspaces:
     - name: source
       workspace: workspace
-  - name: label-check
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-checks)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
-  - name: fbc-label-check
-    params:
-    - name: POLICY_NAMESPACE
-      value: fbc_checks
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-optional)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
   - name: deprecated-base-image-check
     params:
     - name: BASE_IMAGES_DIGESTS
@@ -897,8 +835,6 @@
       value: $(tasks.build-container.results.IMAGE_DIGEST)
     - name: BASE_IMAGE
       value: $(tasks.inspect-image.results.BASE_IMAGE)
-    runAfter:
-    - fbc-label-check
     taskRef:
       name: fbc-validation
       version: "0.1"
@@ -1115,37 +1051,6 @@
     workspaces:
     - name: source
       workspace: workspace
-  - name: label-check
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-checks)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
-  - name: optional-label-check
-    params:
-    - name: POLICY_NAMESPACE
-      value: optional_checks
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-optional)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
   - name: deprecated-base-image-check
     params:
     - name: BASE_IMAGES_DIGESTS
@@ -1412,37 +1317,6 @@
     workspaces:
     - name: source
       workspace: workspace
-  - name: label-check
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-checks)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
-  - name: optional-label-check
-    params:
-    - name: POLICY_NAMESPACE
-      value: optional_checks
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-optional)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
   - name: deprecated-base-image-check
     params:
     - name: BASE_IMAGES_DIGESTS
@@ -1698,37 +1572,6 @@
     workspaces:
     - name: source
       workspace: workspace
-  - name: label-check
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-checks)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
-  - name: optional-label-check
-    params:
-    - name: POLICY_NAMESPACE
-      value: optional_checks
-    runAfter:
-    - inspect-image
-    taskRef:
-      name: label-check
-      version: "0.1"
-    when:
-    - input: $(params.skip-optional)
-      operator: in
-      values:
-      - "false"
-    workspaces:
-    - name: workspace
-      workspace: workspace
   - name: clair-scan
     params:
     - name: image-digest
```

**Comment by lcarva** [comment]
@dirgim, @MartinBasti ptal

**Comment by lcarva** [comment]
Looks like a change to the e2e tests is required. On it.

**Review by zregvart — APPROVED** [review]
:+1: I would wait for a review from the folk on the integration team

**Review by dirgim — APPROVED** [review]
LGTM, @jsztuka can you verify that the fbc testing will work ok with these changes?

**Comment by jsztuka** [comment]
Just wanted to make sure the places after removing those label checks are correct. After checking it with kustomize, everything seems to be in the right place.

**Review by jsztuka — APPROVED** [review]
lgtm

**Pull request merged**
