### PR TITLE
Do not use in-memory emptyDir for source-build task

### PR DESCRIPTION
**Pull request by tkdchen**
Meanwhile, lower the resources.limits.memory.

Haven't noticed the revert PR https://github.com/redhat-appstudio/build-definitions/pull/612 during the review of https://github.com/redhat-appstudio/build-definitions/pull/621. Thanks for the reminding by @mmorhun

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Review by chmeliik — APPROVED** [review]
LGTM

I assume this is a result of an offline discussion? Would you mind updating the commit message and/or PR description with the reason for this change?

**Comment by tkdchen** [comment]
> LGTM
> 
> I assume this is a result of an offline discussion? Would you mind updating the commit message and/or PR description with the reason for this change?

@chmeliik You are right, it's a result from an offline discussion. Updated in the description.

**Comment by tkdchen** [comment]
This error looks not relative to this pr
```
[build-service-suite Build templates E2E test] HACBS pipelines build-definitions ec pipelines [BeforeAll] runs ec pipeline pipelines/enterprise-contract.yaml [build, HACBS, pipeline, build-templates-e2e]
  [BeforeAll] /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:385
  [It] /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:423

  [PANICKED] Test Panicked
  In [BeforeAll] at: /usr/local/go/src/runtime/panic.go:260 @ 10/27/23 11:23:19.902

  runtime error: invalid memory address or nil pointer dereference

  Full Stack Trace
    github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1.(*PipelineRun).GetName(...)
    	/github.com/redhat-appstudio/e2e-tests/vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go:62
    github.com/redhat-appstudio/e2e-tests/pkg/utils/has.(*HasController).WaitForComponentPipelineToBeFinished(0xc0011364a0, 0xc000ac58c0, {0x0, 0x0}, 0x2, 0xc001aaa030)
    	/github.com/redhat-appstudio/e2e-tests/pkg/utils/has/components.go:120 +0x17d
    github.com/redhat-appstudio/e2e-tests/tests/build.glob..func2.1.9.1()
    	/github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:411 +0x385
```

**Comment by mkosiarc** [comment]
> This error looks not relative to this pr
> 
> ```
> [build-service-suite Build templates E2E test] HACBS pipelines build-definitions ec pipelines [BeforeAll] runs ec pipeline pipelines/enterprise-contract.yaml [build, HACBS, pipeline, build-templates-e2e]
>   [BeforeAll] /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:385
>   [It] /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:423
> 
>   [PANICKED] Test Panicked
>   In [BeforeAll] at: /usr/local/go/src/runtime/panic.go:260 @ 10/27/23 11:23:19.902
> 
>   runtime error: invalid memory address or nil pointer dereference
> 
>   Full Stack Trace
>     github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1.(*PipelineRun).GetName(...)
>     	/github.com/redhat-appstudio/e2e-tests/vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go:62
>     github.com/redhat-appstudio/e2e-tests/pkg/utils/has.(*HasController).WaitForComponentPipelineToBeFinished(0xc0011364a0, 0xc000ac58c0, {0x0, 0x0}, 0x2, 0xc001aaa030)
>     	/github.com/redhat-appstudio/e2e-tests/pkg/utils/has/components.go:120 +0x17d
>     github.com/redhat-appstudio/e2e-tests/tests/build.glob..func2.1.9.1()
>     	/github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:411 +0x385
> ```

I saw similar failures in my pipelines, rerunning (if necessary several times) often helps.

**Comment by MartinBasti** [comment]
Pls report to QE that we have repeating race condition error in CI

**Comment by mkosiarc** [comment]
> Pls report to QE that we have repeating race condition error in CI

Would forum-rhtap-qe be the proper place for that?

**Review by rcerven — APPROVED** [review]

**Pull request merged**
