### PR TITLE
Test the EC pipelines with e2e tests

### PR DESCRIPTION
**Pull request by lcarva**
https://issues.redhat.com/browse/HACBS-2475

### CODE REVIEW

**Comment by lcarva** [comment]
This needs this change first before merging: https://github.com/redhat-appstudio/e2e-tests/pull/733

**Comment by lcarva** [comment]
/retest

Logs are already gone...

**Comment by lcarva** [comment]
Need to move the `ec-pipelines` label to skip the is-chains-running check due to lack of permissions: https://github.com/redhat-appstudio/e2e-tests/pull/737

**Review by zregvart — APPROVED** [review]

**Comment by lcarva** [comment]
This is failing with:
```
      <*errors.StatusError | 0xc000928f00>: 
      secrets "quay-repository" is forbidden: User "system:serviceaccount:tekton-ci:appstudio-pipeline" cannot get resource "secrets" in API group "" in the namespace "e2e-secrets"
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "secrets \"quay-repository\" is forbidden: User \"system:serviceaccount:tekton-ci:appstudio-pipeline\" cannot get resource \"secrets\" in API group \"\" in the namespace \"e2e-secrets\"",
              Reason: "Forbidden",
              Details: {
                  Name: "quay-repository",
                  Group: "",
                  Kind: "secrets",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 403,
          },
      }
  occurred
```

That's expected... the user here shouldn't have direct access to that secret. I need to think of a different approach here. We'll likely need to leverage Application and Components.

Moving back to draft.

**Pull request closed without merging**
